### ISSUE TITLE
Other country than Czech?

### ISSUE THREAD

**Issue by rakucmr** [jkubos/osm-address-extractor#1]
Will this work with other countries?

**Comment by jkubos** [comment]
Hi, I am afraid not. There are 2 Czech Republic-specific data sources: postcodes and addresses. Also rules used in OSM may differ for your country.

However, this lib may be useful for inspiration how to handle big amount of OSM data and how OSM is structured.

**Comment by rakucmr** [comment]
OSM format isn't he same for all countries? And I think in all countries are postcodes and addresses.

**Comment by jkubos** [comment]
I am not that deep in OSM to tell you about differences among countries, but I've noticed there are some country-specific rules. For example here: http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative and http://wiki.openstreetmap.org/wiki/Nominatim/Country_Address_Format and http://wiki.openstreetmap.org/wiki/Name_finder/Address_format 

The reason I used CZ-specific extra data was poor quality of OSM data - for example postcodes were completely unreliable.
